language: scala
jdk: oraclejdk8
scala:
  - 2.12.6

jobs:
  include:

    - stage: build & generate reports
      script:
        - sbt ++$TRAVIS_SCALA_VERSION coverage test
        - sbt ++$TRAVIS_SCALA_VERSION coverageReport
        - sbt ++$TRAVIS_SCALA_VERSION codacyCoverage

    - stage: build & publish docker images
      if: branch = master
      script:
        - echo "Pushing to docker hub..."
        - docker login -u "matek2305" -p "$DOCKER_PASSWORD"
        - sbt ++$TRAVIS_SCALA_VERSION docker:publish
        - echo "Pushing to heroku registry..."
        - docker login -u _ -p "$HEROKU_API_KEY" registry.heroku.com
        - docker tag matek2305/djamoe-betting-engine registry.heroku.com/djamoe/web
        - docker push registry.heroku.com/djamoe/web

    - stage: release app in heroku
      if: branch = master
      script:
        - heroku container:release web -a djamoe
